FROM python:3.12-slim

RUN apt-get update && \
    apt-get install -y --no-install-recommends ffmpeg inotify-tools && \
    rm -rf /var/lib/apt/lists/*

RUN pip install --no-cache-dir ffmpeg-python

WORKDIR /scripts
